name: Angular Build

# {1}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {2}
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      # {3}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    # {4}
    - name: Install dependencies
      run: npm ci
      
    # {5}
    - name: Build
      run: npm run build
    # {6}
    - name: Run tests
      run: npm test